%% HRL file generated by ERLSOM
%%
%% It is possible (and in some cases necessary) to change the name of
%% the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.


-type anyAttrib()  :: {{string(),    %% name of the attribute
                        string()},   %% namespace
                       string()}.    %% value

-type anyAttribs() :: [anyAttrib()] | undefined.

%% xsd:QName values are translated to #qname{} records.
-record(qname, {uri :: string(),
                localPart :: string(),
                prefix :: string(),
                mappedPrefix :: string()}).



-record(body, {anyAttribs :: anyAttribs(),
	'Error' :: 'messages-error'() | undefined,
	route :: ['messages-route'()] | undefined}).

-type body() :: #body{}.


-record('messages-route', {anyAttribs :: anyAttribs(),
	tag :: string() | undefined,
	message :: 'messages-message'()}).

-type 'messages-route'() :: #'messages-route'{}.


-record('messages-message', {anyAttribs :: anyAttribs(),
	id :: string() | undefined,
	creator :: string() | undefined,
	startBoundary :: string() | undefined,
	startBoundaryStr :: string() | undefined,
	endBoundary :: string() | undefined,
	endBoundaryStr :: string() | undefined,
	sendToBuses :: boolean() | undefined,
	interval :: ['messages-interval'()] | undefined}).

-type 'messages-message'() :: #'messages-message'{}.


-record('messages-interval', {anyAttribs :: anyAttribs(),
	startDay :: string() | undefined,
	startTime :: string() | undefined,
	endDay :: string() | undefined,
	endTime :: string() | undefined}).

-type 'messages-interval'() :: #'messages-interval'{}.


-record('messages-error', {anyAttribs :: anyAttribs(),
	shouldRetry :: boolean() | undefined,
	'#text' :: string() | undefined}).

-type 'messages-error'() :: #'messages-error'{}.