%% HRL file generated by ERLSOM
%%
%% It is possible (and in some cases necessary) to change the name of
%% the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.


-type anyAttrib()  :: {{string(),    %% name of the attribute
                        string()},   %% namespace
                       string()}.    %% value

-type anyAttribs() :: [anyAttrib()] | undefined.

%% xsd:QName values are translated to #qname{} records.
-record(qname, {uri :: string(),
                localPart :: string(),
                prefix :: string(),
                mappedPrefix :: string()}).



-record(body, {anyAttribs :: anyAttribs(),
	copyright :: string() | undefined,
	'Error' :: 'schedule-error'() | undefined,
	route :: ['schedule-route'()] | undefined}).

-type body() :: #body{}.


-record('schedule-tr', {anyAttribs :: anyAttribs(),
	blockID :: string() | undefined,
	stop :: ['schedule-trstop'()] | undefined}).

-type 'schedule-tr'() :: #'schedule-tr'{}.


-record('schedule-header', {anyAttribs :: anyAttribs(),
	stop :: ['schedule-headerstop'()] | undefined}).

-type 'schedule-header'() :: #'schedule-header'{}.


-record('schedule-route', {anyAttribs :: anyAttribs(),
	tag :: string() | undefined,
	title :: string() | undefined,
	scheduleClass :: string() | undefined,
	serviceClass :: string() | undefined,
	direction :: string() | undefined,
	header :: 'schedule-header'() | undefined,
	tr :: ['schedule-tr'()] | undefined}).

-type 'schedule-route'() :: #'schedule-route'{}.


-record('schedule-trstop', {anyAttribs :: anyAttribs(),
	tag :: string() | undefined,
	epochTime :: string() | undefined,
	'#text' :: string() | undefined}).

-type 'schedule-trstop'() :: #'schedule-trstop'{}.


-record('schedule-headerstop', {anyAttribs :: anyAttribs(),
	tag :: string() | undefined,
	'#text' :: string() | undefined}).

-type 'schedule-headerstop'() :: #'schedule-headerstop'{}.


-record('schedule-error', {anyAttribs :: anyAttribs(),
	shouldRetry :: boolean() | undefined,
	'#text' :: string() | undefined}).

-type 'schedule-error'() :: #'schedule-error'{}.