%% HRL file generated by ERLSOM
%%
%% It is possible (and in some cases necessary) to change the name of
%% the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.


-type anyAttrib()  :: {{string(),    %% name of the attribute
                        string()},   %% namespace
                       string()}.    %% value

-type anyAttribs() :: [anyAttrib()] | undefined.

%% xsd:QName values are translated to #qname{} records.
-record(qname, {uri :: string(),
                localPart :: string(),
                prefix :: string(),
                mappedPrefix :: string()}).



-record(body, {anyAttribs :: anyAttribs(),
	copyright :: string() | undefined,
	'Error' :: 'vehicle-error'() | undefined,
	vehicle :: ['vehicle-vehicle'()] | undefined,
	lastTime :: 'vehicle-time'() | undefined}).

-type body() :: #body{}.


-record('vehicle-time', {anyAttribs :: anyAttribs(),
	time :: string() | undefined}).

-type 'vehicle-time'() :: #'vehicle-time'{}.


-record('vehicle-vehicle', {anyAttribs :: anyAttribs(),
	id :: string() | undefined,
	routeTag :: string() | undefined,
	dirTag :: string() | undefined,
	lat :: string() | undefined,
	lon :: string() | undefined,
	secsSinceReport :: integer() | undefined,
	predictable :: boolean() | undefined,
	heading :: string() | undefined,
	speedKmHr :: string() | undefined,
	leadingVehicleId :: string() | undefined}).

-type 'vehicle-vehicle'() :: #'vehicle-vehicle'{}.


-record('vehicle-error', {anyAttribs :: anyAttribs(),
	shouldRetry :: boolean() | undefined,
	'#text' :: string() | undefined}).

-type 'vehicle-error'() :: #'vehicle-error'{}.